version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
install:
- cmd: choco install gitversion.portable -pre -y
before_build:
- cmd: >-
    nuget restore

    gitversion /l console /output buildserver /updateAssemblyInfo
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
artifacts:
- path: '*.nupkg'
  name: NuGet Package
deploy:
- provider: NuGet
  api_key:
    secure: k1LO5/Ap8IjBhpszOmEfhRdcpY3PI+6uPLaYufsA7L+J+Jctg1QXKTSAiCwC3fVO
  on:
    branch: master
    APPVEYOR_REPO_TAG: True
